# Generated by Django 4.2 on 2023-04-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lista_de_entregas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entrega', models.CharField(max_length=40)),
                ('estado', models.CharField(default='Por hacer', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='stock_local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.TextField(max_length=40)),
                ('fecha_vencimiento', models.CharField(max_length=40)),
                ('fecha_elaboracion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=40)),
                ('apellido', models.TextField(max_length=40)),
                ('nick_name', models.TextField(max_length=40)),
            ],
        ),
    ]
